# Site settings
title: Chris Matthias
email: chris.matthias@gmail.com
description: ""
#baseurl: "http://local.chrismatthias.com"
#url: "http://local.chrismatthias.com/"
twitter_username: thetrickster88
github_username:  thetrickster
timezone: America/New_York

# Build settings
destination: ../local-chrismatthias-com
markdown: kramdown
permalink: /:categories/:title/

# Exclude Files
exclude: ["CNAME", "bower_components", "node_modules", "bower.json", "Gemfile", "Gemfile.lock", "less", "Gruntfile.js", "package.json", "README.md", "js/lib", "js/modernizr.js", "js/app-compiled.js", "js/app.js"]
# Include files from root
include: ["favicion.*", "apple-touch-icon-*"]